### ISSUE TITLE
Error when trying to autocomplete

### ISSUE THREAD

**Issue by lpil** [dermusikman/sonicpi.vim#15]
![screen shot 2016-03-07 at 08 48 47](https://cloud.githubusercontent.com/assets/6134406/13564425/73386b0e-e441-11e5-93fb-41b278102d6c.png)

I'm using neovim, and my used plugins and config can be found here: https://github.com/lpil/vimrc/blob/master/home/.vimrc

**Comment by dermusikman** [comment]
Does this remain a problem? If it can't be duplicated in mainstream vim, I'm inclined to think it an issue with neovim.

**Comment by lpil** [comment]
Unsure. Let's close this an reopen if someone else reports it.

**Comment by dermusikman** [comment]
Sounds good. Closing the issue for now.
