### ISSUE TITLE
Send selected to server?

### ISSUE THREAD

**Issue by hughshuwang** [dermusikman/sonicpi.vim#21]
Hi there,

Thanks for creating this to make the Sonic Pi experience much much more awesome with vim - I'm wondering what should I do to be able to send a selected chunk of code to the sonic pi server, instead of the whole file I'm currently editing.

Thanks

**Comment by R-Bas** [comment]
Hi,

I add the same exact need, here are my modifications to plugin/sonicpi.vim to make this work :
```
@@ -68,6 +68,10 @@ function! s:SonicPiSendBuffer()
   execute "silent w !" . g:sonicpi_command . " " . g:sonicpi_send
 endfunction

+function! s:SonicPiSendSelection()
+  execute "silent '<,'>w !" . g:sonicpi_command . " " . g:sonicpi_send
+endfunction
+
 function! s:SonicPiStop()
   execute "silent !" . g:sonicpi_command . " " . g:sonicpi_stop
   if g:vim_redraw
@@ -77,10 +81,12 @@ endfunction

 " Export public API
 command! -nargs=0 SonicPiSendBuffer call s:SonicPiSendBuffer()
+command! -nargs=0 SonicPiSendSelection call s:SonicPiSendSelection()
 command! -nargs=0 SonicPiStop call s:SonicPiStop()

 " Set keymaps in Normal mode
 function! s:load_keymaps()
   nnoremap <leader>r :SonicPiSendBuffer<CR>
+  nnoremap <leader>e :SonicPiSendSelection<CR>
   nnoremap <leader>S :SonicPiStop<CR>
 endfunction
```

With this you can select the chunk of code you want then hit Escape and finally \<leader>e to send it to sonic-pi.

**Comment by dermusikman** [comment]
That looks great! Would you be willing to submit a pull request, @R-Bas?

**Comment by R-Bas** [comment]
Sure,
I also wrote a command to send just the current line.
Do you want me to include this as well in the pull request @dermusikman ?

**Comment by dermusikman** [comment]
That sounds great, yeah! Please do.
