### ISSUE TITLE
Don't 'stop' when changing buffers

### ISSUE THREAD

**Issue by benrhughes** [dermusikman/sonicpi.vim#8]
Hi,
Thanks so much for this plugin - I really love it. One thing that I find annoying though is that changing buffers in vim sends the 'stop' command to sonic-pi. I have a 'utils' file with a heap of common functions, and I'll often want to work on them in one buffer while playing the 'main' buffer.

If you don't think this is a generally useful change, could you give me a hint about what I'd need to change in the vimscript to do it myself? I can't see anything obvious.

Cheers,

Ben

**Comment by dermusikman** [comment]
I'm so glad you like it! I haven't experienced your problem before, so let
me make sure I understand the details.

I use multiple buffers with vsplit with no issues. Are you editing both
buffers at the same time in a split, or switching buffers entirely? Can you
give me a step-by-step to duplicating the issue?

**Comment by dermusikman** [comment]
(I'll do some troubleshooting in a day or two, rest assured. In the midst
of some life transitions, presently.)

**Comment by benrhughes** [comment]
Switching between splits is OK, switching buffers with :bnext or :bprev to
a buffer with a sonic pi/Ruby file loaded causes sonic pi to stop playing.
I think maybe it's the sonic pi detection code that runs on buffer entry?

Cheers,

Ben

**Comment by dermusikman** [comment]
I suspect you may be right. I'm happy to look at that as soon as I get the
chance, and you're welcome to submit a PR if you find a solution before I
do. Hopefully I can push that up tonight or tomorrow

**Comment by benrhughes** [comment]
Great, thanks.

Ben

**Comment by benrhughes** [comment]
Having a closer look at the plugin, I think this is the issue:

```
let s:activep = system(g:sonicpi_command.' stop 2>/dev/null && echo -n $?')  
```

AFAICT, we're calling the 'stop' command to check if sonic-pi-cli is installed. Removing 'stop' from the command seems to fix my issue without any side effects that I've noticed, but I assume it was done like that to begin with for a reason, so I'm not sure about sending a PR for the change.

**Comment by dermusikman** [comment]
You nailed it, thank you :)

I had chosen the OSC command "/stop" as an innocuous way of testing connection to the server, with the erroneous assumption that it wouldn't have affected performance. (I hadn't tried changing buffers during a run before.) I've changed that test, now, to "/version", which accomplishes the same goal without stopping the run. If the GUI is running, you'll see a message in the log that a new action has started, but it should have no ill effect on performance.

With this latest merge, I'm able to change buffers successfully without negatively affecting performance.

Thanks for bringing this up! Don't hesitate to let me know if you come across any more bugs, or have more feature requests!

**Comment by dermusikman** [comment]
(Oh, and for clarity: I wasn't running "/stop" to test if `sonic_pi` was present, but to confirm that it could successfully connect to the sonic-pi-server. Just wanted to mention in case there are more issues around this in the future, or you decide to submit any PRs. Thanks again!)

**Comment by benrhughes** [comment]
Excellent, thanks for the fix and the info.

Cheers,

Ben
